// Двуязычные строки для раздела встреч (RU/ES). Внешние гости-испанцы видят UI
// на испанском, русские — на русском. Язык берётся из профиля / выбора гостя.
export type MeetLang = "ru" | "es";

export const meetStr: Record<MeetLang, Record<string, string>> = {
  ru: {
    meetings: "Встречи",
    meetingsDesc: "Видеозвонки прямо в браузере: демонстрация экрана, приглашение внешних участников по ссылке. Запись и субтитры — по желанию.",
    start: "Начать встречу",
    starting: "Создаём…",
    ongoing: "Идут сейчас",
    past: "Прошедшие",
    enter: "Войти",
    startedAt: "Начата",
    hasRecording: "есть запись",
    empty: "Встреч ещё не было.",
    meetingTitle: "Встреча",
    captions: "Субтитры",
    invite: "Пригласить",
    end: "Завершить",
    mic: "Микрофон",
    camera: "Камера",
    screen: "Экран",
    leave: "Выйти",
    chat: "Чат",
    endConfirm: "Завершить встречу для всех?",
    linkCopied: "Ссылка-приглашение скопирована (действует 24 ч)",
    linkFail: "Не удалось создать ссылку",
    connectTitle: "Подключение к встрече",
    enterName: "Введите имя, чтобы присоединиться.",
    yourName: "Ваше имя",
    subLang: "Язык субтитров",
    join: "Присоединиться",
    connecting: "Подключение…",
    invalidLink: "Ссылка недействительна или истекла",
    askNew: "Попросите организатора прислать новую.",
    cantEnter: "Не удалось войти во встречу",
    ended: "Встреча завершена.",
    notFound: "Встреча не найдена или недоступна.",
    backToList: "← К списку встреч",
    connectingMeeting: "Подключение к встрече…",
    rec: "Запись",
    recStart: "Запись",
    recStop: "Стоп",
    recStarting: "Запуск…",
    recActive: "Идёт запись",
    recProcessing: "Обработка записи…",
    recReady: "Запись готова",
    recFailed: "Запись не удалась",
    recNone: "Записи нет",
    download: "Скачать mp4",
    transcribe: "Расшифровать",
    transcribeQueued: "В очереди на расшифровку",
    transcribing: "Расшифровка…",
    transcribed: "Расшифровка готова",
    transcribeFailed: "Ошибка расшифровки",
    openTranscript: "Открыть расшифровку",
    recordingSection: "Запись и расшифровка",
    rename: "Переименовать",
    save: "Сохранить",
    cancel: "Отмена",
    duration: "Длительность",
    statusActive: "Идёт",
    statusEnded: "Завершена",
    joinRoom: "Войти в комнату",
    meetingInfo: "О встрече",
    created: "Создана",
    loading: "Загрузка…",
  },
  es: {
    meetings: "Reuniones",
    meetingsDesc: "Videollamadas en el navegador: compartir pantalla e invitar a participantes externos por enlace. Grabación y subtítulos opcionales.",
    start: "Iniciar reunión",
    starting: "Creando…",
    ongoing: "En curso",
    past: "Pasadas",
    enter: "Entrar",
    startedAt: "Iniciada",
    hasRecording: "con grabación",
    empty: "Aún no hubo reuniones.",
    meetingTitle: "Reunión",
    captions: "Subtítulos",
    invite: "Invitar",
    end: "Finalizar",
    mic: "Micrófono",
    camera: "Cámara",
    screen: "Pantalla",
    leave: "Salir",
    chat: "Chat",
    endConfirm: "¿Finalizar la reunión para todos?",
    linkCopied: "Enlace de invitación copiado (válido 24 h)",
    linkFail: "No se pudo crear el enlace",
    connectTitle: "Unirse a la reunión",
    enterName: "Escribe tu nombre para unirte.",
    yourName: "Tu nombre",
    subLang: "Idioma de subtítulos",
    join: "Unirse",
    connecting: "Conectando…",
    invalidLink: "El enlace no es válido o ha expirado",
    askNew: "Pide al organizador uno nuevo.",
    cantEnter: "No se pudo entrar a la reunión",
    ended: "La reunión ha finalizado.",
    notFound: "Reunión no encontrada o no disponible.",
    backToList: "← A la lista de reuniones",
    connectingMeeting: "Conectando a la reunión…",
    rec: "Grabación",
    recStart: "Grabar",
    recStop: "Detener",
    recStarting: "Iniciando…",
    recActive: "Grabando",
    recProcessing: "Procesando grabación…",
    recReady: "Grabación lista",
    recFailed: "Fallo de grabación",
    recNone: "Sin grabación",
    download: "Descargar mp4",
    transcribe: "Transcribir",
    transcribeQueued: "En cola para transcribir",
    transcribing: "Transcribiendo…",
    transcribed: "Transcripción lista",
    transcribeFailed: "Error de transcripción",
    openTranscript: "Abrir transcripción",
    recordingSection: "Grabación y transcripción",
    rename: "Renombrar",
    save: "Guardar",
    cancel: "Cancelar",
    duration: "Duración",
    statusActive: "En curso",
    statusEnded: "Finalizada",
    joinRoom: "Entrar a la sala",
    meetingInfo: "Sobre la reunión",
    created: "Creada",
    loading: "Cargando…",
  },
};
